---
## Tor section
- name: restart tor
  service:
    name: tor
    state: restarted

## App/securedrop section
- name: restart apache2
  service:
    name: apache2
    state: restarted

## Here, we list apparmor before haveged to ensure the correct AppArmor
## profile is loaded prior to restarting haveged
- name: restart apparmor
  service:
    name: apparmor
    state: restarted

- name: restart haveged
  service:
    name: haveged
    state: restarted
