---
# Playbook to update SecureDrop VMs to install Focal packages from a local repo
#
# Steps to use this playbook:
#
#   1. On host machine, build packages with `make build-debs-focal`
#   2. On host machine, provision local apt repo with `vagrant up apt-local`
#   3. Switch to Admin Workstation
#   3. Continue with prod provisioning as far as `./securedrop-admin sdconfig`
#   5. Run `source admin/.venv3/bin/activate` (so ansible commands work)
#   6. Run `cd install_files/ansible-base`
#   7. Run `ansible-playbook -vv --diff securedrop-apt-local.yml`
#   8. Proceed with `./securedrop-admin install`

- name: Configure prod host to prioritize local packages.
  environment:
    LC_ALL: C
  max_fail_percentage: 0
  any_errors_fatal: yes
  hosts: securedrop
  tasks:
    - name: Add apt public key for local repo.
      apt_key:
        data: "{{ lookup('file', '../../molecule/upgrade/files/apt-test.pub') }}"
        state: present

    - name: Add local repo
      apt_repository:
        repo: deb [arch=amd64] http://10.0.1.7 focal main
        state: present
        update_cache: yes
  become: yes
