#!/usr/bin/env ansible-playbook
---
# Configures SecureDrop dotfiles persistence on Admin and Journalist
# Workstations. Should be run after the servers have been installed.
- name: Configure Tails workstation.
  hosts: localhost
  max_fail_percentage: 0
  any_errors_fatal: yes
  connection: local
  gather_facts: yes
  environment:
    LC_ALL: C
  roles:
    - role: tails-config
      tags: tails-config
  tasks:
    - name: Configuration complete.
      debug:
        msg: >-
          Successfully configured Tor and set up desktop bookmarks for SecureDrop!
          You will see a notification appear on your screen when Tor is ready.
          Please reboot your Workstation to take advantage of the SecureDrop Menu.

          The Journalist Interface's Tor onion URL is: http://{{ journalist_iface.stdout }}
          The Source Interfaces's Tor onion URL is: http://{{ source_iface.stdout }}
          {% if find_v3_aths_info_result.matched > 1 %}
          SSH aliases are set up. You can use them with 'ssh app' and 'ssh mon'.
          {% endif %}
