codecov:
  disable_default_path_fixes: false
ignore:
  - "securedrop/loaddata.py"
  - "securedrop/upload-screenshots.py"
  - "securedrop/qa_loader.py"
  - "securedrop/create-dev-data.py"
  - "securedrop/specialstrings.py"
