[tool.black]
line-length = 100
target-version = ["py38"]
exclude = "securedrop/config.py"
extend-exclude = ".venv"

[tool.isort]
line_length = 100
profile = "black"

[tool.mypy]
ignore_missing_imports = true
no_implicit_optional = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_configs = true
python_version = "3.8"
plugins = "sqlmypy"

[[tool.mypy.overrides]]
module = [
    "securedrop.tests.*",
    "admin.tests.*"
]
disallow_untyped_defs = false
