---
# Read the Onion URL from the Tor info files that were fetched back during
# installation. On the Admin Workstation, these files will be present
# after running the playbooks, but on the Journalist Workstation, they must
# be copied manually by the Admin.

- name: Check for v3 Source Interface file
  stat:
    path: app-sourcev3-ths
  register: v3_source_file

- name: Check for v3 Journalist Interface file
  stat:
    path: app-journalist.auth_private
  register: v3_journalist_file

- name: Look up v3 Source Interface URL.
  command: grep -Po '.{56}\.onion' app-sourcev3-ths
  changed_when: false
  register: sourcev3_interface_lookup_result
  when: v3_source_file.stat.exists == true

- name: Look up v3 Journalist Interface URL.
  command: awk -F ':' '{print $1 ".onion"}' app-journalist.auth_private
  changed_when: false
  register: journalistv3_interface_lookup_result
  when: v3_source_file.stat.exists == true

- name: Create desktop shortcut parent directories.
  file:
    state: directory
    path: "{{ item }}"
  with_items: "{{ tails_config_desktop_icon_directories }}"

- name: Set normal user ownership on subset of directories.
  become: yes
  file:
    state: directory
    path: "{{ item }}"
    owner: amnesia
    group: amnesia
  # Only set normal user ownership for files in ~amnesia.
  when: item.startswith(tails_config_amnesia_home)
  with_items: "{{ tails_config_desktop_icon_directories }}"

- name: Set the right variable for source
  set_fact:
    source_iface: "{{ sourcev3_interface_lookup_result }}"

- name: Set the right variable for journalist
  set_fact:
    journalist_iface: "{{ journalistv3_interface_lookup_result }}"

- debug:
    var: source_iface

# Storing as host fact so we can loop over the data in one task.
- name: Assemble desktop icon info.
  set_fact:
    _securedrop_desktop_icon_info:
      - src: desktop-source-icon.j2
        filename: source.desktop
        onion_url: "{{ source_iface.stdout }}"
      - src: desktop-journalist-icon.j2
        filename: journalist.desktop
        onion_url: "{{ journalist_iface.stdout }}"

- name: Create SecureDrop interface desktop icons.
  become: yes
  template:
    src: "{{ item.0.src }}"
    dest: "{{ item.1 }}/{{ item.0.filename }}"
    owner: amnesia
    group: amnesia
    mode: "0700"
  with_nested:
    - "{{ _securedrop_desktop_icon_info }}"
    - "{{ tails_config_desktop_icon_directories }}"
