---
# Reuse validation logic.
- include: "{{ role_path }}/../validate/tasks/validate_tails_environment.yml"

- include: copy_dotfiles.yml

- include: configure_torrc_additions.yml

- include: create_desktop_shortcuts.yml

- include: install_shell_extension.yml

- include: configure_network_hook.yml

- name: Check that we are on an admin workstation
  stat:
    path: group_vars/all/site-specific
  register: site_specific_result

- include: create_ssh_aliases.yml
  when: site_specific_result.stat.exists
