---
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  yamllint

platforms:
  - name: app-staging
    box: bento/ubuntu-16.04
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
      - "vm.network 'private_network', ip: '10.0.1.2'"
      - "ssh.insert_key = false"
    memory: 1024
    private_ip: 10.0.1.2
    groups:
      - securedrop_application_server
      - securedrop
      - staging

  - name: mon-staging
    box: bento/ubuntu-16.04
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
      - "vm.network 'private_network', ip: '10.0.1.3'"
      - "ssh.insert_key = false"
    memory: 1024
    private_ip: 10.0.1.3
    groups:
      - securedrop_monitor_server
      - securedrop
      - staging

provisioner:
  name: ansible
  lint: |
    ansible-lint
  inventory:
    links:
      group_vars: ../../install_files/ansible-base/group_vars
      host_vars: ../../install_files/ansible-base/host_vars
  env:
    ANSIBLE_ROLES_PATH: ".molecule/roles"
    ANSIBLE_GATHER_TIMEOUT: "120"
  options:
    skip-tags: "local_build"
    e: "@ansible-override-vars.yml"
  config_options:
    defaults:
      interpreter_python: auto
    ssh_connection:
      pipelining: True
  playbooks:
    side_effect: side_effect.yml

scenario:
  name: vagrant-packager
  test_sequence:
    - destroy
    - create
    - converge
    - side_effect
verifier:
  name: testinfra
  lint: |
    flake8
