---
# The FPF apt repository hosts Debian packages for use with SecureDrop.
# For a full list of the packages, see:
#
#   https://developers.securedrop.org/en/latest/apt_repo.html
#
# To request source packages for the grsecurity-patched kernels, see:
#
#   https://github.com/freedomofpress/securedrop/blob/develop/SOURCE_OFFER
#
# For testing/QA, set this URL to another apt server. You must also update
# the associated public key for the apt repo for testing/QA.
apt_repo_url: https://apt.freedom.press

# By default, install packages from the apt-repo, but under
# staging hosts we'll prefer locally-built deb packages
install_local_packages: False

# Basename for GPG public key used for the FPF apt repository.
# May be overridden in staging to install from a test/QA server,
# the Release file for which will *not* be signed with the prod key.
apt_repo_pubkey_files:
  - fpf-signing-key-2021.pub

# As of v2.0.0, only Focal is supported.
apt_repo_target_distro: "{{ ansible_distribution_release }}"
