---
- include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"

- include: install_packages.yml

- include: post_ubuntu_install_checks.yml

- include: create_users.yml

- include: setup_etc_hosts.yml

- include: harden_dns.yml

- include: cron_apt.yml
  tags:
    - reboot

- include: remove_unused_packages.yml

- include: apt_upgrade.yml

- include: sysctl.yml

- include: disable_swap.yml

- include: remove_kernel_modules.yml
