---
# Configuration for unattended upgrades is almost exclusively managed by the
# securedrop-config package under Focal.

- name: Ensure apt-daily and apt-daily-upgrade services are unmasked, started and enabled.
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  with_items:
    - 'apt-daily'
    - 'apt-daily-upgrade'
  tags:
    - apt
    - unattended-upgrades

- name: Ensure apt-daily and apt-daily-upgrade timers are started, and enabled.
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - 'apt-daily.timer'
    - 'apt-daily-upgrade.timer'
  tags:
    - apt
    - unattended-upgrades
