---
- name: Backup torrc file
  copy:
    src: /etc/tor/torrc
    dest: /etc/tor/torrc.bak
    remote_src: yes
  when: ("V3 services only" in compare_result.stdout)

- name: Remove v2 service definitions from torrc.
  shell: >
    awk '!/HiddenServiceVersion 2/'
    RS="HiddenServiceDir" ORS="HiddenServiceDir"
    /etc/tor/torrc.bak | sed '$d' > /etc/tor/torrc
  when: ("V3 services only" in compare_result.stdout)

- name: Check Tor config
  command: tor --verify-config
  register: tor_verify
  become_user: debian-tor
  when: ("V3 services only" in compare_result.stdout)

- name: Verify that Tor config is valid
  assert:
    that:
      - "'Configuration was valid' in tor_verify.stdout"
    fail_msg:
      - "Removal of obsolete V2 configuration blocks failed - the new"
      - "configuration file is invalid."
  when: ("V3 services only" in compare_result.stdout)

- name: Verify that V2 config directives are removed
  assert:
    that:
      - "'Onion service version 2 are deprecated' not in tor_verify.stdout"
    fail_msg:
      - "V2 configurations were not successfully removed. Please review /etc/tor/torrc"
      - "and manually remove any v2 service definitions."
  when: ("V3 services only" in compare_result.stdout)

- name: Remove backup torrc file
  file:
    state: absent
    path: /etc/tor/torrc.bak
  when: ("V3 services only" in compare_result.stdout)

- name: Remove v2 tor source directory
  file:
    state: absent
    path: /var/lib/tor/services/source
  when: ("V3 services only" in compare_result.stdout)

- name: Remove v2 tor journalist directory
  file:
    state: absent
    path: /var/lib/tor/services/journalist
  when: ("V3 services only" in compare_result.stdout)

- name: Remove v2 tor ssh directory
  file:
    state: absent
    path: /var/lib/tor/services/ssh
  when: ("V3 services only" in compare_result.stdout)

- name: Remove v2 source_url application file
  file:
    state: absent
    path: /var/lib/securedrop/source_v2_url
  when: ("V3 services only" in compare_result.stdout)
