---
- name: Perform apt upgrades
  hosts: securedrop
  become: yes
  tasks:
    - name: Perform safe upgrade
      apt:
        update_cache: yes
        upgrade: yes

- name: Lay out app testing deps
  hosts: securedrop_application_server
  max_fail_percentage: 0
  any_errors_fatal: yes
  roles:
    - role: app-test
      tags: app-test

  tasks:
    - name: Reset database
      command: ./manage.py reset
      args:
        chdir: /var/www/securedrop

    - name: Slap in latest loaddata script
      copy:
        src: ../../securedrop/loaddata.py
        dest: /var/www/securedrop/loaddata.py
        mode: 0555

    - name: Insert journalist test user
      command: /var/www/securedrop/loaddata.py
      args:
        chdir: /var/www/securedrop
  become: yes
