---
- name: Look up Tor v3 URL info
  command: cat /var/lib/tor/services/sourcev3/hostname
  changed_when: false
  register: v3_onion_url_lookup_result
  # File may not exist, depending on host config
  failed_when: false

- name: Expose source v3 onion service info to app
  copy:
    dest: /var/lib/securedrop/source_v3_url
    owner: www-data
    group: www-data
    mode: "0644"
    content: |
      {{ v3_onion_url_lookup_result.stdout|default('') }}
  notify:
    - restart apache2
