---
- include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"

- include: fetch_tor_config.yml
  when: fetch_tor_client_auth_configs

- include: dh_moduli.yml

- include: ssh.yml

- include: iptables.yml
  tags:
    - iptables
    - permissions
