---
build_ossec_deb_pkg_dependencies:
  - "libpcre2-dev"
  - "{{ 'libevent-dev' if securedrop_target_distribution == 'focal' else 'libevent1-dev' }}"

ossec_server_hostname: ossec-server
ossec_version: 3.6.0
# Parent directory for performing build operations. All files related
# to build, including source tarball, will be created inside this dir.
build_path: /tmp/build

repo_src_path: "{{ build_path }}/ossec-{{ purpose }}"
ossec_build_dir: "{{ build_path }}/ossec-{{ purpose }}-{{ ossec_version }}+{{ securedrop_target_distribution }}-amd64"

# Destination on Ansible controller where built deb packages will be placed.
ossec_build_deb_package_local_dest_dir: "../../build/{{ securedrop_target_distribution }}/"

ossec_build_rsync_generic_opts:
  - "--exclude=*.git"
  - "--exclude=*.deb"

# Needed to support ansible v1 :(
# See explanation from b291059d556d6cdb11c8ab8d68eab96436cb9f69
ossec_build_rsync_ansible_hack_opt:
  - "--rsync-path='sudo rsync'"

ossec_source_checksum: sha256:653828a19137b8a7e98af65e873318f7bb48137fe1e61b80577e13c316e04708
