---
- name: Install mailing utilities.
  apt:
    pkg: "{{ postfix_dependencies }}"
    state: present
  tags:
    - apt
    - postfix

- name: Copy postfix /etc/aliases file to route root mail alerts to OSSEC.
  copy:
    src: aliases
    dest: /etc/aliases
  notify: update aliases
  tags:
    - postfix

- name: Create outbound mapping for postfix_from_address in /etc/postfix/generic.
  copy:
    content: "ossec@{{ postfix_hostname }} {{ postfix_from_address }}\n"
    dest: /etc/postfix/generic
  notify: update generic_maps
  when: postfix_from_address != ""
  tags:
    - postfix

- name: Remove /etc/postfix/generic database because postfix_from_address is empty.
  file:
    state: absent
    dest: "{{ item }}"
  with_items:
    - /etc/postfix/generic
    - /etc/postfix/generic.db
  when: postfix_from_address == ""
  tags:
    - postfix

- name: Configure SASL password for SMTP relay.
  template:
    src: sasl_passwd
    dest: /etc/postfix/sasl_passwd
    mode: "0400"
  notify: update sasl_passwd db
  tags:
    - postfix
    - permissions

- name: Configure Postfix to strip SMTP headers.
  copy:
    src: header_checks
    dest: /etc/postfix/header_checks
  notify: postmap_header_checks
  tags:
    - postfix
    - hardening

- name: Copy Postfix config file.
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
  notify: restart postfix
  tags:
    - postfix

- name: Configure Postfix service.
  service:
    name: postfix
    state: "{{ 'started' if postfix_enable_service else 'stopped' }}"
    enabled: "{{ postfix_enable_service }}"
