[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "redwood"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
]

[tool.maturin]
compatibility = "linux"
