---
# Support dynamic lookups for Qubes host IPs. The staging vars
# in the Ansible config still assume hardcoded Vagrant-only IPs.
app_ip: "{{ hostvars['app-staging']['ansible_default_ipv4'].address }}"
monitor_ip: "{{ hostvars['mon-staging']['ansible_default_ipv4'].address }}"

# Use hardcoded username from the manual VM provisioning step.
ssh_users: sdadmin

securedrop_target_distribution: xenial

# Inform the Ansible logic we're targeting Qubes staging VMs,
# helps to customize the reboot logic.
securedrop_staging_qubes_env: True
