---
  # Ansible doesn't support notifying handlers based on file existence, results,
  # e.g. via registered `stat` results, only on changed=true task results,
  # so let's craft a task that returns changed=true if-and-only-if a file exists.
- name: Check if reboot is required due to inactive grsecurity lock.
  command: /bin/true
  args:
    # This task won't actually create anything, given the task is simply `true`,
    # but leveraging the `creates` arg allows us to run the task conditionally,
    # based on file existence, which is an accurate indicator of whether a reboot
    # is required.
    creates: /proc/sys/kernel/grsecurity/grsec_lock
  notify: reboot
  tags:
    - reboot
