---
  # The default motd shipped with Ubuntu displays system load averages.
  # The calls used to gather the system load information are blocked
  # by grsecurity, which causes error messages like this on login:
  #
  # From 10.0.2.2: denied RWX mmap of <anonymous mapping>
  # by /usr/bin/landscape-sysinfo[landscape-sysin:3393] uid/euid:0/0
  # gid/egid:0/0, parent
  # /usr/share/landscape/landscape-sysinfo.wrapper[50-landscape-sy:3386]
  # uid/euid:0/0 gid/egid:0/0
  #
  # So, let's remove the default motd so that doesn't happen.
- name: Remove MOTD pam module from SSH logins.
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: pam.motd
    state: absent
    backup: yes
  tags:
    - motd
    - grsecurity

# The `securedrop-grsec` package named below is a metapackage that depends
# on a custom-compiled linux-image binary package hosted in the FPF repo.
# To request the source package for the grsecurity-patched kernel, see:
#
#   https://github.com/freedomofpress/securedrop/blob/develop/SOURCE_OFFER
- name: Install the grsecurity-patched kernel from the FPF repo.
  apt:
    pkg: securedrop-grsec
    state: latest
  async: 500
  poll: 10
  when: not install_local_packages|default(False)
  tags:
    - apt
    - grsec
    - kernel
    - hardening
