---
  # Check whether grsecurity is already configured,
  # since that fact will be used in multiple includes.
- include: check_installation.yml

  # Install the grsec kernel prior to running unattended-upgrades to avoid
  # reboots
- include: from_fpf_repo_install_grsec.yml
  tags:
    - grsec

- include: from_local_pkg_install_grsec.yml
  when: install_local_packages|default(False)
  tags:
    - grsec

- include: clean_packages.yml

- include: apply_grsec_lock.yml
  tags:
    - reboot
    - grsec
