---
- name: Install paxctl.
  apt:
    pkg: paxctl
    state: present
  tags:
    - apt

- name: Check paxctl headers on grub binaries.
  command: paxctl -vQ {{ item }}
  # Read-only task, so don't report changed
  changed_when: false
  # The first time this task is run, the grub binaries won't have
  # their headers converted yet, which will cause paxctl to exit 1.
  # We'll catch that error and respond accordingly in the next task.
  failed_when: false
  register: paxctl_grub_header_check
  with_items:
    - /usr/sbin/grub-probe
    - /usr/sbin/grub-mkdevicemap
    - /usr/bin/grub-script-check

- name: Adjust paxctl headers on grub binaries.
  command: paxctl -z{{ paxctl_header_type[ansible_distribution_release] }}E {{ item.item }}
  with_items: "{{ paxctl_grub_header_check.results }}"
  when: >
    item.stdout != '- PaX flags: --------E--- ['+item.item+']'
    or item.rc != 0
