---
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  yamllint

platforms:
  - name: app-staging
    box: bento/ubuntu-16.04
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
      - "vm.network 'private_network', ip: '10.0.1.2'"
      - "ssh.insert_key = false"
    memory: 1024
    private_ip: 10.0.1.2
    groups:
      - securedrop_application_server
      - securedrop
      - staging

  - name: mon-staging
    box: bento/ubuntu-16.04
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
      - "vm.network 'private_network', ip: '10.0.1.3'"
      - "ssh.insert_key = false"
    memory: 1024
    private_ip: 10.0.1.3
    groups:
      - securedrop_monitor_server
      - securedrop
      - staging

provisioner:
  name: ansible
  lint: |
    ansible-lint
  config_options:
    defaults:
      interpreter_python: auto
  options:
    e: "@ansible-override-vars.yml"
  playbooks:
    converge: ../../install_files/ansible-base/securedrop-staging.yml
    create: ../libvirt-staging-xenial/create.yml
    destroy: ../libvirt-staging-xenial/destroy.yml
    prepare: ../libvirt-staging-xenial/prepare.yml
  env:
    ANSIBLE_CONFIG: ../../install_files/ansible-base/ansible.cfg

scenario:
  name: virtualbox-staging-xenial
  test_sequence:
    - destroy
    - create
    - converge
    - verify
verifier:
  name: testinfra
  lint: |
    flake8
  directory: ../testinfra
  options:
    n: auto
    v: 2
